author: "Tobe O <thosakwe@gmail.com>"
description: "Run package:http through a proxy."
homepage: "https://github.com/thosakwe/http_proxy_client.git"
name: "http_proxy_client"
version: "1.0.0"
dependencies: 
  http: "^0.11.0"
dev_dependencies:
  angel_common: ^1.0.0-beta
  test: ^0.12.0